### ISSUE TITLE
ConnectionStrategy.close_connection should be async

### ISSUE THREAD

**Issue by p7g** [fellowapp/asyncio-connection-pool#2]
In some cases closing a connection is an asynchronous operation. One example is an asyncio StreamWriter, where [`close`](https://docs.python.org/3/library/asyncio-stream.html#asyncio.StreamWriter.close) doesn't synchronously close the connection; it should be followed with `await writer.wait_closed()`.

Because the `ConnectionStrategy.close_connection` can only be synchronous, in cases where the close operation is async it's possible to have many excess connections still open despite the pool thinking that it has closed them already. This can lead to "too many open files" exceptions, and more generally it violates the pool's `max_size` or `burst_limit`.

Changing this will break the API, though a migration is trivial.

Since it's possible that the pool will be used while `await`ing the connection being closed, the adjustment to the `in_use` attribute should be moved to happen after the `await`.

**Comment by nirvana-msu** [comment]
This is definitely true. I would say in most (all?) cases you'd need `close_connection` to be async. Even taking the example of the `asyncio_connection_pool.contrib.aioredis` pool that comes with the package, [proper](https://aioredis.readthedocs.io/en/v1.3.1/examples.html#low-level-connection-usage-example) way to close the connection is not just 
```python
conn.close()
```
, but
```python
conn.close()
await conn.wait_closed()
```
